apiVersion: apps/{{ .Values.global.apiVersion }}
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  labels:
{{ include "stock-trading-helper.labels" . | indent 4 }}

spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
{{ include "stock-trading-helper.labels" . | indent 6 }}
  template:
    metadata:
      labels:
{{ include "stock-trading-helper.labels" . | indent 8 }}
    spec:
      containers:
        {{- with .Values.image }}
        - name: {{ $.Release.Name }}
          image: {{ .repository }}:{{ .tag }}
          imagePullPolicy: {{ .pullPolicy }}
          ports:
            - containerPort: {{ .containerPort }}
        {{- end }}
          {{- with .Values.resources }}
          resources:
            limits:
              cpu: {{ .limits.cpu }}
            requests:
              cpu: {{ .requests.cpu }}
          {{- end }}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- range .Values.imagePullSecrets }}
        - name: {{ . }}
        {{- end }}
      {{- end }}
