{{- if .Values.autoscaling.enabled }}
apiVersion: autoscaling/{{ .Values.global.apiVersion }}
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Release.Name }}-hpa
  labels:
{{ include "stock-trading-helper.labels" . | indent 4 }}

spec:
  scaleTargetRef:
    apiVersion: apps/{{ .Values.global.apiVersion }}
    kind: Deployment
    name: {{ .Release.Name }}-deployment
  {{- with .Values.autoscaling }}
  minReplicas: {{ .minReplicas }}
  maxReplicas: {{ .maxReplicas }}
  targetCPUUtilizationPercentage: {{ .targetCPUUtilizationPercentage }}
  {{- end }}
{{- end }}