{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/{{ .Values.global.apiVersion }}
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
{{ include "stock-trading-helper.labels" . | indent 4 }}

spec:
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - secretName: {{ .secretName }}
      {{- if .hosts }}
      hosts:
        {{- range .hosts }}
        - {{ . }}
        {{- end }}
      {{- end }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host }}
      http:
        paths:
          {{- range .paths }}
          - pathType: {{ .type }}
            path: {{ .path }}
            backend:
              service:
                name: {{ $.Release.Name }}-service
                port:
                  number: {{ $.Values.service.port }}
          {{- end }}
    {{- end }}
{{- end }}
