version: 2.1

executors:
  executor:
    machine: true

jobs:
  build:
    executor: executor
    steps:
      - checkout
      - run: make build
      - run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
      - run: make push

  deploy:
    executor: executor
    steps:
      - checkout
      - run: curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
      - run: chmod 700 get_helm.sh
      - run: ./get_helm.sh
      - run: |
          sed -i -e "s,\$K8S_SERVER,${K8S_SERVER},g" \
                 -e "s,\$CERTIFICATE_AUTHORITY_DATA,${CERTIFICATE_AUTHORITY_DATA},g" \
                 -e "s,\$CLIENT_CERTIFICATE_DATA,${CLIENT_CERTIFICATE_DATA},g" \
                 -e "s,\$CLIENT_KEY_DATA,${CLIENT_KEY_DATA},g" .circleci/kube
      - when:
          condition:
            equal: [ master, << pipeline.git.branch >> ]
          steps:
            - run: make deploy
      - when:
          condition:
            equal: [ staging, << pipeline.git.branch >> ]
          steps:
            - run: make deploy VALUES=values.staging.yaml NAMESPACE=project-sth-staging
      - when:
          condition:
            equal: [ develop, << pipeline.git.branch >> ]
          steps:
            - run: make deploy VALUES=values.dev.yaml NAMESPACE=project-sth-dev

workflows:
  version: 2

  build_deploy:
    jobs:
      - build
      - deploy:
          context:
            - chammanganti.com-k8s
          requires:
            - build
